name: Build ImmortalWrt

on:
  # 手动触发工作流
  workflow_dispatch:
  # 定时自动触发，这里设置为每周六凌晨 3 点
  schedule:
    - cron: '0 19 * * *'

env:
  # 手动触发输入参数默认值
  REPO_URL: 'https://github.com/immortalwrt/immortalwrt.git'
  REPO_BRANCH: 'master'
  CONFIG_FILE: 'configs/pass.config'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
          g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
          libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
          libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
          ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
          python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
          unzip vim wget xmlto xxd zlib1g-dev zstd
          
   
      - name: Clone source code
        run: |
          git clone --depth=1 ${{ env.REPO_URL }} -b ${{ env.REPO_BRANCH }} immortalwrt
        working-directory: ${{ github.workspace }}

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
        working-directory: ${{ github.workspace }}/immortalwrt
        
      - name: Load custom configuration
        run: |
         cp ${{ github.workspace }}/${{ env.CONFIG_FILE }} .config
         working-directory: ${{ github.workspace }}/immortalwrt
        
      - name: Build firmware
        run: |
          make -j$(nproc) V=s
        working-directory: ${{ github.workspace }}/immortalwrt

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-firmware
          path: ${{ github.workspace }}/immortalwrt/bin/targets/*/*/*.bin
