name: Build ImmortalWrt

on:
  # 手动触发工作流
  workflow_dispatch:
  # 定时自动触发，这里设置为每周六凌晨 3 点
  schedule:
    - cron: '0 19 * * 0'

env:
  # 手动触发输入参数默认值
  REPO_URL: 'https://github.com/immortalwrt/immortalwrt.git'
  REPO_BRANCH: 'master'
  CONFIG_FILE: '/configs/pass.config'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
            python3-distutils python3-setuptools rsync subversion swig time \
            xsltproc zlib1g-dev

      - name: Clone source code
        run: |
          git clone ${{ env.REPO_URL }} -b ${{ env.REPO_BRANCH }} immortalwrt
        working-directory: ${{ github.workspace }}

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
        working-directory: ${{ github.workspace }}/immortalwrt

      - name: Load custom configuration
        run: |
          if [ -n "${{ env.CONFIG_FILE }}" ]; then
            cp ${{ github.workspace }}/${{ env.CONFIG_FILE }} .config
          else
            # 如果没有提供自定义配置文件，可使用默认配置
            make defconfig
          fi
        working-directory: ${{ github.workspace }}/immortalwrt

      - name: Build firmware
        run: |
          make -j$(nproc) V=s
        working-directory: ${{ github.workspace }}/immortalwrt

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: immortalwrt-firmware
          path: ${{ github.workspace }}/immortalwrt/bin/targets/*/*/*.bin
